/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { invoiceStrictHttpResponse } from '../../invoice-strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BillingAccountSearchRequest } from '../../models/billing-account-search-request';
import { Pageable } from '../../models/pageable';
import { PageBillingAccountResponse } from '../../models/page-billing-account-response';

export interface SearchAccount$Params {
  pageable: Pageable;
      body: BillingAccountSearchRequest
}

export function searchAccount(http: HttpClient, rootUrl: string, params: SearchAccount$Params, context?: HttpContext): Observable<invoiceStrictHttpResponse<PageBillingAccountResponse>> {
  const rb = new RequestBuilder(rootUrl, searchAccount.PATH, 'post');
  if (params) {
    rb.query('pageable', params.pageable, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as invoiceStrictHttpResponse<PageBillingAccountResponse>;
    })
  );
}

searchAccount.PATH = '/api/v1/billing/search';
