/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from "@angular/common/http";
import { Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";

import { invoiceBaseService } from "../invoice-base-service";
import { invoiceApiConfiguration } from "../invoice-api-configuration";
import { invoiceStrictHttpResponse } from "../invoice-strict-http-response";

import { ping } from "../fn/ping-controller/ping";
import { Ping$Params } from "../fn/ping-controller/ping";
import { PingResponse } from "../models/ping-response";

@Injectable({ providedIn: "root" })
export class invoicePingControllerService extends invoiceBaseService {
  constructor(config: invoiceApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `ping()` */
  static readonly PingPath = "/api/v1/ping";

  /**
   * Pings the api.
   *
   * Returns information about the api
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ping()` instead.
   *
   * This method doesn't expect any request body.
   */
  ping$Response(
    params?: Ping$Params,
    context?: HttpContext,
  ): Observable<invoiceStrictHttpResponse<PingResponse>> {
    return ping(this.http, this.rootUrl, params, context);
  }

  /**
   * Pings the api.
   *
   * Returns information about the api
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ping$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ping(params?: Ping$Params, context?: HttpContext): Observable<PingResponse> {
    return this.ping$Response(params, context).pipe(
      map((r: invoiceStrictHttpResponse<PingResponse>): PingResponse => r.body),
    );
  }
}
