/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from "@angular/common/http";
import { Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";

import { invoiceBaseService } from "../invoice-base-service";
import { invoiceApiConfiguration } from "../invoice-api-configuration";
import { invoiceStrictHttpResponse } from "../invoice-strict-http-response";

import { getAllNotifications } from "../fn/notification-api/get-all-notifications";
import { GetAllNotifications$Params } from "../fn/notification-api/get-all-notifications";
import { getNotificationsOfAccountHolder } from "../fn/notification-api/get-notifications-of-account-holder";
import { GetNotificationsOfAccountHolder$Params } from "../fn/notification-api/get-notifications-of-account-holder";
import { markNotificationsAsRead } from "../fn/notification-api/mark-notifications-as-read";
import { MarkNotificationsAsRead$Params } from "../fn/notification-api/mark-notifications-as-read";
import { NotificationResponse } from "../models/notification-response";
import { PageNotificationResponse } from "../models/page-notification-response";

/**
 * API to manage notifications
 */
@Injectable({ providedIn: "root" })
export class invoiceNotificationApiService extends invoiceBaseService {
  constructor(config: invoiceApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllNotifications()` */
  static readonly GetAllNotificationsPath =
    "/api/v1/notification/notifications";

  /**
   * Retrieves all notifications.
   *
   * Returns a list of notifications.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllNotifications()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getAllNotifications$Response(
    params: GetAllNotifications$Params,
    context?: HttpContext,
  ): Observable<invoiceStrictHttpResponse<PageNotificationResponse>> {
    return getAllNotifications(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves all notifications.
   *
   * Returns a list of notifications.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllNotifications$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getAllNotifications(
    params: GetAllNotifications$Params,
    context?: HttpContext,
  ): Observable<PageNotificationResponse> {
    return this.getAllNotifications$Response(params, context).pipe(
      map(
        (
          r: invoiceStrictHttpResponse<PageNotificationResponse>,
        ): PageNotificationResponse => r.body,
      ),
    );
  }

  /** Path part for operation `markNotificationsAsRead()` */
  static readonly MarkNotificationsAsReadPath =
    "/api/v1/notification/mark-read";

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `markNotificationsAsRead()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  markNotificationsAsRead$Response(
    params: MarkNotificationsAsRead$Params,
    context?: HttpContext,
  ): Observable<
    invoiceStrictHttpResponse<
      | "100 CONTINUE"
      | "101 SWITCHING_PROTOCOLS"
      | "102 PROCESSING"
      | "103 EARLY_HINTS"
      | "103 CHECKPOINT"
      | "200 OK"
      | "201 CREATED"
      | "202 ACCEPTED"
      | "203 NON_AUTHORITATIVE_INFORMATION"
      | "204 NO_CONTENT"
      | "205 RESET_CONTENT"
      | "206 PARTIAL_CONTENT"
      | "207 MULTI_STATUS"
      | "208 ALREADY_REPORTED"
      | "226 IM_USED"
      | "300 MULTIPLE_CHOICES"
      | "301 MOVED_PERMANENTLY"
      | "302 FOUND"
      | "302 MOVED_TEMPORARILY"
      | "303 SEE_OTHER"
      | "304 NOT_MODIFIED"
      | "305 USE_PROXY"
      | "307 TEMPORARY_REDIRECT"
      | "308 PERMANENT_REDIRECT"
      | "400 BAD_REQUEST"
      | "401 UNAUTHORIZED"
      | "402 PAYMENT_REQUIRED"
      | "403 FORBIDDEN"
      | "404 NOT_FOUND"
      | "405 METHOD_NOT_ALLOWED"
      | "406 NOT_ACCEPTABLE"
      | "407 PROXY_AUTHENTICATION_REQUIRED"
      | "408 REQUEST_TIMEOUT"
      | "409 CONFLICT"
      | "410 GONE"
      | "411 LENGTH_REQUIRED"
      | "412 PRECONDITION_FAILED"
      | "413 PAYLOAD_TOO_LARGE"
      | "413 REQUEST_ENTITY_TOO_LARGE"
      | "414 URI_TOO_LONG"
      | "414 REQUEST_URI_TOO_LONG"
      | "415 UNSUPPORTED_MEDIA_TYPE"
      | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
      | "417 EXPECTATION_FAILED"
      | "418 I_AM_A_TEAPOT"
      | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
      | "420 METHOD_FAILURE"
      | "421 DESTINATION_LOCKED"
      | "422 UNPROCESSABLE_ENTITY"
      | "423 LOCKED"
      | "424 FAILED_DEPENDENCY"
      | "425 TOO_EARLY"
      | "426 UPGRADE_REQUIRED"
      | "428 PRECONDITION_REQUIRED"
      | "429 TOO_MANY_REQUESTS"
      | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
      | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
      | "500 INTERNAL_SERVER_ERROR"
      | "501 NOT_IMPLEMENTED"
      | "502 BAD_GATEWAY"
      | "503 SERVICE_UNAVAILABLE"
      | "504 GATEWAY_TIMEOUT"
      | "505 HTTP_VERSION_NOT_SUPPORTED"
      | "506 VARIANT_ALSO_NEGOTIATES"
      | "507 INSUFFICIENT_STORAGE"
      | "508 LOOP_DETECTED"
      | "509 BANDWIDTH_LIMIT_EXCEEDED"
      | "510 NOT_EXTENDED"
      | "511 NETWORK_AUTHENTICATION_REQUIRED"
    >
  > {
    return markNotificationsAsRead(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `markNotificationsAsRead$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  markNotificationsAsRead(
    params: MarkNotificationsAsRead$Params,
    context?: HttpContext,
  ): Observable<
    | "100 CONTINUE"
    | "101 SWITCHING_PROTOCOLS"
    | "102 PROCESSING"
    | "103 EARLY_HINTS"
    | "103 CHECKPOINT"
    | "200 OK"
    | "201 CREATED"
    | "202 ACCEPTED"
    | "203 NON_AUTHORITATIVE_INFORMATION"
    | "204 NO_CONTENT"
    | "205 RESET_CONTENT"
    | "206 PARTIAL_CONTENT"
    | "207 MULTI_STATUS"
    | "208 ALREADY_REPORTED"
    | "226 IM_USED"
    | "300 MULTIPLE_CHOICES"
    | "301 MOVED_PERMANENTLY"
    | "302 FOUND"
    | "302 MOVED_TEMPORARILY"
    | "303 SEE_OTHER"
    | "304 NOT_MODIFIED"
    | "305 USE_PROXY"
    | "307 TEMPORARY_REDIRECT"
    | "308 PERMANENT_REDIRECT"
    | "400 BAD_REQUEST"
    | "401 UNAUTHORIZED"
    | "402 PAYMENT_REQUIRED"
    | "403 FORBIDDEN"
    | "404 NOT_FOUND"
    | "405 METHOD_NOT_ALLOWED"
    | "406 NOT_ACCEPTABLE"
    | "407 PROXY_AUTHENTICATION_REQUIRED"
    | "408 REQUEST_TIMEOUT"
    | "409 CONFLICT"
    | "410 GONE"
    | "411 LENGTH_REQUIRED"
    | "412 PRECONDITION_FAILED"
    | "413 PAYLOAD_TOO_LARGE"
    | "413 REQUEST_ENTITY_TOO_LARGE"
    | "414 URI_TOO_LONG"
    | "414 REQUEST_URI_TOO_LONG"
    | "415 UNSUPPORTED_MEDIA_TYPE"
    | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
    | "417 EXPECTATION_FAILED"
    | "418 I_AM_A_TEAPOT"
    | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
    | "420 METHOD_FAILURE"
    | "421 DESTINATION_LOCKED"
    | "422 UNPROCESSABLE_ENTITY"
    | "423 LOCKED"
    | "424 FAILED_DEPENDENCY"
    | "425 TOO_EARLY"
    | "426 UPGRADE_REQUIRED"
    | "428 PRECONDITION_REQUIRED"
    | "429 TOO_MANY_REQUESTS"
    | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
    | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
    | "500 INTERNAL_SERVER_ERROR"
    | "501 NOT_IMPLEMENTED"
    | "502 BAD_GATEWAY"
    | "503 SERVICE_UNAVAILABLE"
    | "504 GATEWAY_TIMEOUT"
    | "505 HTTP_VERSION_NOT_SUPPORTED"
    | "506 VARIANT_ALSO_NEGOTIATES"
    | "507 INSUFFICIENT_STORAGE"
    | "508 LOOP_DETECTED"
    | "509 BANDWIDTH_LIMIT_EXCEEDED"
    | "510 NOT_EXTENDED"
    | "511 NETWORK_AUTHENTICATION_REQUIRED"
  > {
    return this.markNotificationsAsRead$Response(params, context).pipe(
      map(
        (
          r: invoiceStrictHttpResponse<
            | "100 CONTINUE"
            | "101 SWITCHING_PROTOCOLS"
            | "102 PROCESSING"
            | "103 EARLY_HINTS"
            | "103 CHECKPOINT"
            | "200 OK"
            | "201 CREATED"
            | "202 ACCEPTED"
            | "203 NON_AUTHORITATIVE_INFORMATION"
            | "204 NO_CONTENT"
            | "205 RESET_CONTENT"
            | "206 PARTIAL_CONTENT"
            | "207 MULTI_STATUS"
            | "208 ALREADY_REPORTED"
            | "226 IM_USED"
            | "300 MULTIPLE_CHOICES"
            | "301 MOVED_PERMANENTLY"
            | "302 FOUND"
            | "302 MOVED_TEMPORARILY"
            | "303 SEE_OTHER"
            | "304 NOT_MODIFIED"
            | "305 USE_PROXY"
            | "307 TEMPORARY_REDIRECT"
            | "308 PERMANENT_REDIRECT"
            | "400 BAD_REQUEST"
            | "401 UNAUTHORIZED"
            | "402 PAYMENT_REQUIRED"
            | "403 FORBIDDEN"
            | "404 NOT_FOUND"
            | "405 METHOD_NOT_ALLOWED"
            | "406 NOT_ACCEPTABLE"
            | "407 PROXY_AUTHENTICATION_REQUIRED"
            | "408 REQUEST_TIMEOUT"
            | "409 CONFLICT"
            | "410 GONE"
            | "411 LENGTH_REQUIRED"
            | "412 PRECONDITION_FAILED"
            | "413 PAYLOAD_TOO_LARGE"
            | "413 REQUEST_ENTITY_TOO_LARGE"
            | "414 URI_TOO_LONG"
            | "414 REQUEST_URI_TOO_LONG"
            | "415 UNSUPPORTED_MEDIA_TYPE"
            | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
            | "417 EXPECTATION_FAILED"
            | "418 I_AM_A_TEAPOT"
            | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
            | "420 METHOD_FAILURE"
            | "421 DESTINATION_LOCKED"
            | "422 UNPROCESSABLE_ENTITY"
            | "423 LOCKED"
            | "424 FAILED_DEPENDENCY"
            | "425 TOO_EARLY"
            | "426 UPGRADE_REQUIRED"
            | "428 PRECONDITION_REQUIRED"
            | "429 TOO_MANY_REQUESTS"
            | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
            | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
            | "500 INTERNAL_SERVER_ERROR"
            | "501 NOT_IMPLEMENTED"
            | "502 BAD_GATEWAY"
            | "503 SERVICE_UNAVAILABLE"
            | "504 GATEWAY_TIMEOUT"
            | "505 HTTP_VERSION_NOT_SUPPORTED"
            | "506 VARIANT_ALSO_NEGOTIATES"
            | "507 INSUFFICIENT_STORAGE"
            | "508 LOOP_DETECTED"
            | "509 BANDWIDTH_LIMIT_EXCEEDED"
            | "510 NOT_EXTENDED"
            | "511 NETWORK_AUTHENTICATION_REQUIRED"
          >,
        ):
          | "100 CONTINUE"
          | "101 SWITCHING_PROTOCOLS"
          | "102 PROCESSING"
          | "103 EARLY_HINTS"
          | "103 CHECKPOINT"
          | "200 OK"
          | "201 CREATED"
          | "202 ACCEPTED"
          | "203 NON_AUTHORITATIVE_INFORMATION"
          | "204 NO_CONTENT"
          | "205 RESET_CONTENT"
          | "206 PARTIAL_CONTENT"
          | "207 MULTI_STATUS"
          | "208 ALREADY_REPORTED"
          | "226 IM_USED"
          | "300 MULTIPLE_CHOICES"
          | "301 MOVED_PERMANENTLY"
          | "302 FOUND"
          | "302 MOVED_TEMPORARILY"
          | "303 SEE_OTHER"
          | "304 NOT_MODIFIED"
          | "305 USE_PROXY"
          | "307 TEMPORARY_REDIRECT"
          | "308 PERMANENT_REDIRECT"
          | "400 BAD_REQUEST"
          | "401 UNAUTHORIZED"
          | "402 PAYMENT_REQUIRED"
          | "403 FORBIDDEN"
          | "404 NOT_FOUND"
          | "405 METHOD_NOT_ALLOWED"
          | "406 NOT_ACCEPTABLE"
          | "407 PROXY_AUTHENTICATION_REQUIRED"
          | "408 REQUEST_TIMEOUT"
          | "409 CONFLICT"
          | "410 GONE"
          | "411 LENGTH_REQUIRED"
          | "412 PRECONDITION_FAILED"
          | "413 PAYLOAD_TOO_LARGE"
          | "413 REQUEST_ENTITY_TOO_LARGE"
          | "414 URI_TOO_LONG"
          | "414 REQUEST_URI_TOO_LONG"
          | "415 UNSUPPORTED_MEDIA_TYPE"
          | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
          | "417 EXPECTATION_FAILED"
          | "418 I_AM_A_TEAPOT"
          | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
          | "420 METHOD_FAILURE"
          | "421 DESTINATION_LOCKED"
          | "422 UNPROCESSABLE_ENTITY"
          | "423 LOCKED"
          | "424 FAILED_DEPENDENCY"
          | "425 TOO_EARLY"
          | "426 UPGRADE_REQUIRED"
          | "428 PRECONDITION_REQUIRED"
          | "429 TOO_MANY_REQUESTS"
          | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
          | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
          | "500 INTERNAL_SERVER_ERROR"
          | "501 NOT_IMPLEMENTED"
          | "502 BAD_GATEWAY"
          | "503 SERVICE_UNAVAILABLE"
          | "504 GATEWAY_TIMEOUT"
          | "505 HTTP_VERSION_NOT_SUPPORTED"
          | "506 VARIANT_ALSO_NEGOTIATES"
          | "507 INSUFFICIENT_STORAGE"
          | "508 LOOP_DETECTED"
          | "509 BANDWIDTH_LIMIT_EXCEEDED"
          | "510 NOT_EXTENDED"
          | "511 NETWORK_AUTHENTICATION_REQUIRED" => r.body,
      ),
    );
  }

  /** Path part for operation `getNotificationsOfAccountHolder()` */
  static readonly GetNotificationsOfAccountHolderPath =
    "/api/v1/notification/{accountId}";

  /**
   * Retrieves a billing notifications of a account holder.
   *
   * Returns a list of notifications of an account holder.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getNotificationsOfAccountHolder()` instead.
   *
   * This method doesn't expect any request body.
   */
  getNotificationsOfAccountHolder$Response(
    params: GetNotificationsOfAccountHolder$Params,
    context?: HttpContext,
  ): Observable<invoiceStrictHttpResponse<NotificationResponse>> {
    return getNotificationsOfAccountHolder(
      this.http,
      this.rootUrl,
      params,
      context,
    );
  }

  /**
   * Retrieves a billing notifications of a account holder.
   *
   * Returns a list of notifications of an account holder.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getNotificationsOfAccountHolder$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getNotificationsOfAccountHolder(
    params: GetNotificationsOfAccountHolder$Params,
    context?: HttpContext,
  ): Observable<NotificationResponse> {
    return this.getNotificationsOfAccountHolder$Response(params, context).pipe(
      map(
        (
          r: invoiceStrictHttpResponse<NotificationResponse>,
        ): NotificationResponse => r.body,
      ),
    );
  }
}
