/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { invoiceBaseService } from '../invoice-base-service';
import { invoiceApiConfiguration } from '../invoice-api-configuration';
import { invoiceStrictHttpResponse } from '../invoice-strict-http-response';

import { PageBillingAccountResponse } from '../models/page-billing-account-response';
import { searchAccount } from '../fn/billing-account-api/search-account';
import { SearchAccount$Params } from '../fn/billing-account-api/search-account';


/**
 * API to manage account holders
 */
@Injectable({ providedIn: 'root' })
export class invoiceBillingAccountApiService extends invoiceBaseService {
  constructor(config: invoiceApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `searchAccount()` */
  static readonly SearchAccountPath = '/api/v1/billing/search';

  /**
   * Retrieves a paginating list of account holders.
   *
   * Returns account holder paginated summary.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchAccount()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  searchAccount$Response(params: SearchAccount$Params, context?: HttpContext): Observable<invoiceStrictHttpResponse<PageBillingAccountResponse>> {
    return searchAccount(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves a paginating list of account holders.
   *
   * Returns account holder paginated summary.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchAccount$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  searchAccount(params: SearchAccount$Params, context?: HttpContext): Observable<PageBillingAccountResponse> {
    return this.searchAccount$Response(params, context).pipe(
      map((r: invoiceStrictHttpResponse<PageBillingAccountResponse>): PageBillingAccountResponse => r.body)
    );
  }

}
