/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from "@angular/common/http";
import { Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";

import { invoiceBaseService } from "../invoice-base-service";
import { invoiceApiConfiguration } from "../invoice-api-configuration";
import { invoiceStrictHttpResponse } from "../invoice-strict-http-response";

import { login } from "../fn/authentication-api/login";
import { Login$Params } from "../fn/authentication-api/login";

/**
 * API to perform authentication operations
 */
@Injectable({ providedIn: "root" })
export class invoiceAuthenticationApiService extends invoiceBaseService {
  constructor(config: invoiceApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `login()` */
  static readonly LoginPath = "/api/v1/auth/login";

  /**
   * Login user.
   *
   * Authenticate user.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `login()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login$Response(
    params: Login$Params,
    context?: HttpContext,
  ): Observable<
    invoiceStrictHttpResponse<{
      [key: string]: string;
    }>
  > {
    return login(this.http, this.rootUrl, params, context);
  }

  /**
   * Login user.
   *
   * Authenticate user.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `login$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login(
    params: Login$Params,
    context?: HttpContext,
  ): Observable<{
    [key: string]: string;
  }> {
    return this.login$Response(params, context).pipe(
      map(
        (
          r: invoiceStrictHttpResponse<{
            [key: string]: string;
          }>,
        ): {
          [key: string]: string;
        } => r.body,
      ),
    );
  }
}
