/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from "@angular/common/http";
import { Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";

import { invoiceBaseService } from "../invoice-base-service";
import { invoiceApiConfiguration } from "../invoice-api-configuration";
import { invoiceStrictHttpResponse } from "../invoice-strict-http-response";

import { createInvoices } from "../fn/invoice-tracking-api/create-invoices";
import { CreateInvoices$Params } from "../fn/invoice-tracking-api/create-invoices";
import { getInvoice } from "../fn/invoice-tracking-api/get-invoice";
import { GetInvoice$Params } from "../fn/invoice-tracking-api/get-invoice";
import { InvoiceResponse } from "../models/invoice-response";
import { PageInvoiceResponse } from "../models/page-invoice-response";
import { searchInvoices } from "../fn/invoice-tracking-api/search-invoices";
import { SearchInvoices$Params } from "../fn/invoice-tracking-api/search-invoices";
import { updateInvoices } from "../fn/invoice-tracking-api/update-invoices";
import { UpdateInvoices$Params } from "../fn/invoice-tracking-api/update-invoices";

/**
 * API to manage invoices
 */
@Injectable({ providedIn: "root" })
export class invoiceInvoiceTrackingApiService extends invoiceBaseService {
  constructor(config: invoiceApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateInvoices()` */
  static readonly UpdateInvoicesPath = "/api/v1/invoice/";

  /**
   * Create a new invoice.
   *
   * Creates an new invoice
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateInvoices()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateInvoices$Response(
    params: UpdateInvoices$Params,
    context?: HttpContext,
  ): Observable<invoiceStrictHttpResponse<InvoiceResponse>> {
    return updateInvoices(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new invoice.
   *
   * Creates an new invoice
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateInvoices$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateInvoices(
    params: UpdateInvoices$Params,
    context?: HttpContext,
  ): Observable<InvoiceResponse> {
    return this.updateInvoices$Response(params, context).pipe(
      map(
        (r: invoiceStrictHttpResponse<InvoiceResponse>): InvoiceResponse =>
          r.body,
      ),
    );
  }

  /** Path part for operation `createInvoices()` */
  static readonly CreateInvoicesPath = "/api/v1/invoice/";

  /**
   * Create a new invoice.
   *
   * Creates an new invoice
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createInvoices()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createInvoices$Response(
    params: CreateInvoices$Params,
    context?: HttpContext,
  ): Observable<invoiceStrictHttpResponse<InvoiceResponse>> {
    return createInvoices(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new invoice.
   *
   * Creates an new invoice
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createInvoices$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createInvoices(
    params: CreateInvoices$Params,
    context?: HttpContext,
  ): Observable<InvoiceResponse> {
    return this.createInvoices$Response(params, context).pipe(
      map(
        (r: invoiceStrictHttpResponse<InvoiceResponse>): InvoiceResponse =>
          r.body,
      ),
    );
  }

  /** Path part for operation `searchInvoices()` */
  static readonly SearchInvoicesPath = "/api/v1/invoice/search";

  /**
   * Retrieves a paginating list of invoices.
   *
   * Returns invoice paginated summary.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchInvoices()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  searchInvoices$Response(
    params: SearchInvoices$Params,
    context?: HttpContext,
  ): Observable<invoiceStrictHttpResponse<PageInvoiceResponse>> {
    return searchInvoices(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves a paginating list of invoices.
   *
   * Returns invoice paginated summary.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchInvoices$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  searchInvoices(
    params: SearchInvoices$Params,
    context?: HttpContext,
  ): Observable<PageInvoiceResponse> {
    return this.searchInvoices$Response(params, context).pipe(
      map(
        (
          r: invoiceStrictHttpResponse<PageInvoiceResponse>,
        ): PageInvoiceResponse => r.body,
      ),
    );
  }

  /** Path part for operation `getInvoice()` */
  static readonly GetInvoicePath = "/api/v1/invoice/{invoiceId}";

  /**
   * Retrieves a paginating list of invoices.
   *
   * Returns invoice paginated summary.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getInvoice()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInvoice$Response(
    params: GetInvoice$Params,
    context?: HttpContext,
  ): Observable<invoiceStrictHttpResponse<InvoiceResponse>> {
    return getInvoice(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves a paginating list of invoices.
   *
   * Returns invoice paginated summary.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getInvoice$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInvoice(
    params: GetInvoice$Params,
    context?: HttpContext,
  ): Observable<InvoiceResponse> {
    return this.getInvoice$Response(params, context).pipe(
      map(
        (r: invoiceStrictHttpResponse<InvoiceResponse>): InvoiceResponse =>
          r.body,
      ),
    );
  }
}
