/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { invoiceStrictHttpResponse } from "../../invoice-strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { PingResponse } from "../../models/ping-response";

export interface Ping$Params {}

export function ping(
  http: HttpClient,
  rootUrl: string,
  params?: Ping$Params,
  context?: HttpContext,
): Observable<invoiceStrictHttpResponse<PingResponse>> {
  const rb = new RequestBuilder(rootUrl, ping.PATH, "get");
  if (params) {
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as invoiceStrictHttpResponse<PingResponse>;
      }),
    );
}

ping.PATH = "/api/v1/ping";
