/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvoiceResponse {
  amount?: number;
  billingAccountAddress?: string;
  billingAccountEmail?: string;
  billingAccountId?: string;
  billingAccountName?: string;
  billingAccountNumber?: string;
  invoiceDate?: string;
  invoiceId?: string;
  invoiceNumber?: string;
  status?: 'PENDING' | 'PAID' | 'UNPAID' | 'DUE' | 'OVER_DUE' | 'CANCELLED';
  vatAmount?: number;
}
