/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvoiceCreateRequest {
  amount?: number;
  billingAccountId?: string;
  invoiceDate?: string;
  invoiceNumber?: string;
  status?: 'PENDING' | 'PAID' | 'UNPAID' | 'DUE' | 'OVER_DUE' | 'CANCELLED';
  vatAmount?: number;
}
