/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvoiceSearchRequest {
  accountName?: string;
  amount?: number;
  billingAccountId?: string;
  invoiceDate?: string;
  invoiceId?: string;
  invoiceNumber?: string;
  status?: Array<
    "PENDING" | "PAID" | "UNPAID" | "DUE" | "OVER_DUE" | "CANCELLED"
  >;
}
