/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationSearchRequest {
  accountId?: string;
  fromDate?: string;
  message?: string;
  status?: "READ" | "UNREAD";
  toDate?: string;
  type?: "IMPORTANT" | "GENERAL";
}
