/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationResponse {
  accountName?: string;
  createdAt?: string;
  invoiceDate?: string;
  invoiceId?: string;
  invoiceNumber?: string;
  message?: string;
  notificationId?: string;
  status?: "READ" | "UNREAD";
  type?: "IMPORTANT" | "GENERAL";
}
