/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {
  NgModule,
  ModuleWithProviders,
  SkipSelf,
  Optional,
} from "@angular/core";
import { HttpClient } from "@angular/common/http";
import {
  invoiceApiConfiguration,
  invoiceApiConfigurationParams,
} from "./invoice-api-configuration";

import { invoiceInvoiceTrackingApiService } from "./services/invoice-invoice-tracking-api.service";
import { invoiceNotificationApiService } from "./services/invoice-notification-api.service";
import { invoiceBillingAccountApiService } from "./services/invoice-billing-account-api.service";
import { invoiceAuthenticationApiService } from "./services/invoice-authentication-api.service";
import { invoicePingControllerService } from "./services/invoice-ping-controller.service";

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    invoiceInvoiceTrackingApiService,
    invoiceNotificationApiService,
    invoiceBillingAccountApiService,
    invoiceAuthenticationApiService,
    invoicePingControllerService,
    invoiceApiConfiguration,
  ],
})
export class invoiceModule {
  static forRoot(
    params: invoiceApiConfigurationParams,
  ): ModuleWithProviders<invoiceModule> {
    return {
      ngModule: invoiceModule,
      providers: [
        {
          provide: invoiceApiConfiguration,
          useValue: params,
        },
      ],
    };
  }

  constructor(
    @Optional() @SkipSelf() parentModule: invoiceModule,
    @Optional() http: HttpClient,
  ) {
    if (parentModule) {
      throw new Error(
        "invoiceModule is already loaded. Import in your base AppModule only.",
      );
    }
    if (!http) {
      throw new Error(
        "You need to import the HttpClientModule in your AppModule! \n" +
          "See also https://github.com/angular/angular/issues/20575",
      );
    }
  }
}
