/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from "@angular/core";

/**
 * Global configuration
 */
@Injectable({
  providedIn: "root",
})
export class invoiceApiConfiguration {
  rootUrl: string = "http://localhost:8080";
}

/**
 * Parameters for `invoiceModule.forRoot()`
 */
export interface invoiceApiConfigurationParams {
  rootUrl?: string;
}
