/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { invoiceStrictHttpResponse } from '../../invoice-strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationResponse } from '../../models/notification-response';

export interface GetNotificationsOfAccountHolder$Params {
  accountId: string;
}

export function getNotificationsOfAccountHolder(http: HttpClient, rootUrl: string, params: GetNotificationsOfAccountHolder$Params, context?: HttpContext): Observable<invoiceStrictHttpResponse<NotificationResponse>> {
  const rb = new RequestBuilder(rootUrl, getNotificationsOfAccountHolder.PATH, 'get');
  if (params) {
    rb.path('accountId', params.accountId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as invoiceStrictHttpResponse<NotificationResponse>;
    })
  );
}

getNotificationsOfAccountHolder.PATH = '/api/v1/notification/{accountId}';
