/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { invoiceStrictHttpResponse } from '../../invoice-strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationSearchRequest } from '../../models/notification-search-request';
import { Pageable } from '../../models/pageable';
import { PageNotificationResponse } from '../../models/page-notification-response';

export interface GetAllNotifications$Params {
  pageable: Pageable;
      body: NotificationSearchRequest
}

export function getAllNotifications(http: HttpClient, rootUrl: string, params: GetAllNotifications$Params, context?: HttpContext): Observable<invoiceStrictHttpResponse<PageNotificationResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllNotifications.PATH, 'post');
  if (params) {
    rb.query('pageable', params.pageable, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as invoiceStrictHttpResponse<PageNotificationResponse>;
    })
  );
}

getAllNotifications.PATH = '/api/v1/notification/notifications';
