/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { invoiceStrictHttpResponse } from '../../invoice-strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvoiceCreateRequest } from '../../models/invoice-create-request';
import { InvoiceResponse } from '../../models/invoice-response';

export interface CreateInvoices$Params {
      body: InvoiceCreateRequest
}

export function createInvoices(http: HttpClient, rootUrl: string, params: CreateInvoices$Params, context?: HttpContext): Observable<invoiceStrictHttpResponse<InvoiceResponse>> {
  const rb = new RequestBuilder(rootUrl, createInvoices.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as invoiceStrictHttpResponse<InvoiceResponse>;
    })
  );
}

createInvoices.PATH = '/api/v1/invoice/';
