/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { invoiceStrictHttpResponse } from '../../invoice-strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvoiceResponse } from '../../models/invoice-response';

export interface GetInvoice$Params {
  invoiceId: string;
}

export function getInvoice(http: HttpClient, rootUrl: string, params: GetInvoice$Params, context?: HttpContext): Observable<invoiceStrictHttpResponse<InvoiceResponse>> {
  const rb = new RequestBuilder(rootUrl, getInvoice.PATH, 'get');
  if (params) {
    rb.path('invoiceId', params.invoiceId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as invoiceStrictHttpResponse<InvoiceResponse>;
    })
  );
}

getInvoice.PATH = '/api/v1/invoice/{invoiceId}';
