/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { invoiceStrictHttpResponse } from '../../invoice-strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvoiceSearchRequest } from '../../models/invoice-search-request';
import { Pageable } from '../../models/pageable';
import { PageInvoiceResponse } from '../../models/page-invoice-response';

export interface SearchInvoices$Params {
  pageable: Pageable;
  unPaged?: boolean;
      body: InvoiceSearchRequest
}

export function searchInvoices(http: HttpClient, rootUrl: string, params: SearchInvoices$Params, context?: HttpContext): Observable<invoiceStrictHttpResponse<PageInvoiceResponse>> {
  const rb = new RequestBuilder(rootUrl, searchInvoices.PATH, 'post');
  if (params) {
    rb.query('pageable', params.pageable, {});
    rb.query('unPaged', params.unPaged, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as invoiceStrictHttpResponse<PageInvoiceResponse>;
    })
  );
}

searchInvoices.PATH = '/api/v1/invoice/search';
