/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { invoiceStrictHttpResponse } from "../../invoice-strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { InvoiceCreateRequest } from "../../models/invoice-create-request";
import { InvoiceResponse } from "../../models/invoice-response";

export interface UpdateInvoices$Params {
  body: InvoiceCreateRequest;
}

export function updateInvoices(
  http: HttpClient,
  rootUrl: string,
  params: UpdateInvoices$Params,
  context?: HttpContext,
): Observable<invoiceStrictHttpResponse<InvoiceResponse>> {
  const rb = new RequestBuilder(rootUrl, updateInvoices.PATH, "put");
  if (params) {
    rb.body(params.body, "application/json");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as invoiceStrictHttpResponse<InvoiceResponse>;
      }),
    );
}

updateInvoices.PATH = "/api/v1/invoice/";
